name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      - run: flutter build web
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync --cache-control \'public,max-age=31556926,immutable\' --exclude index.html --delete  build/web/ s3://narlun-frontend
          aws s3 sync --cache-control \'public,must-revalidate,proxy-revalidate,max-age=0\' build/web/ s3://narlun-frontend
