import random


RANDOM_STATUSES = (
    'Hunting for the best coffee nearby',
    'Walking until something interesting happens',
    'Always up for a board game',
    'Looking for a lunch co-conspirator',
    'Pretending this is a productive stroll',
    'On a mission for pastries',
    'Available for spontaneous adventures',
    'Trying a new cafe every week',
    'Happy to chat about films',
    'Down for a quick walk and talk',
    'Collecting good conversation',
    "Searching for the city's best fries",
    'Open to meeting kind weirdos',
    'Taking the scenic route on purpose',
    'Can be persuaded into karaoke',
    'Probably thinking about noodles',
    'Ready for an after-work wander',
    'Looking for museum company',
    'Plotting an excellent picnic',
    'Free for a short tea break',
    'Currently powered by snacks',
    'Trying to touch grass professionally',
    'Seeking a trivia night ally',
    'Would join a dumpling expedition',
    'Out here romanticizing errands',
    'Willing to rate local benches',
    'Open for a tiny side quest',
    'Recovering from too much screen time',
    'Down to talk books and nonsense',
    'I know a suspiciously good bakery',
    'Ready for a sunset walk',
    'Looking for co-op game friends',
    'Trying to be more social than my cat',
    'Can offer strong opinions on pizza',
    'Available for cafe hopping',
    'Taking myself on a little date',
    'Would attend a dramatic dessert tasting',
    'Open to meeting fellow night owls',
    'Looking for lunch break chaos',
    'Trying to make today less boring',
    'On a quest for soup',
    'Happy to explore hidden streets',
    'Can be lured out by good ramen',
    'Collecting tiny urban adventures',
    'Free for one excellent conversation',
    'Down for a quick people-watching session',
    'Seeking someone to split cake with',
    'In the mood for gallery wandering',
    'Just escaped the indoors',
    'Available for tea and light scheming',
    'Looking for park walk company',
    'Ready to discuss absurd life choices',
    'Trying to turn errands into lore',
    'Would join a bookstore expedition',
    'Low battery high curiosity',
    'Open to meeting friendly strangers',
    'Choosing whimsy over efficiency',
    'Can talk about music for hours',
    'Ready for an impromptu coffee',
    'Looking for someone funny to meet',
    'Taking a break from being mysterious',
    'Would absolutely judge croissants with you',
    'Wandering with excellent intentions',
    'Trying to be outside before my plants judge me',
    'Happy to trade local recommendations',
    'Available for a tiny adventure arc',
    'Probably overthinking sandwich options',
    'Would join a dramatic rain walk',
    'Seeking soup and conversation',
    'Out testing my social bravery',
    'Can be bribed with cinnamon rolls',
    'Looking for a casual chat nearby',
    'Trying to collect better memories',
    'Would thrive in a niche little hangout',
    'Open to meeting fellow introvert extroverts',
    'One spontaneous plan away from joy',
    'On a side quest for matcha',
    'Ready for a wholesome detour',
    'Can help you overanalyze movies',
    'Looking for company for a short walk',
    'Currently pretending to be effortlessly cool',
    'Accepting applications for snack accomplices',
    'Trying not to become one with the sofa',
    'Would appreciate a funny conversation',
    'Seeking harmless mischief',
    'Open to cafe chat with nice people',
    'I left the house and should be rewarded',
    'Available for niche recommendations exchange',
    'Would join a sunset appreciation club',
    'Trying to speedrun touching grass',
    'Searching for top tier hot chocolate',
    'Ready for a little neighborhood wander',
    'Can discuss ridiculous internet lore',
    'Looking for an excuse to stay out longer',
    'Emotionally attached to iced coffee',
    'Open to meeting fellow oddballs',
    'Currently in a silly little mood',
    'Ready for tea heroically',
    "Looking for a co-star in today's subplot",
    'I contain multitudes and probably a pastry',
)


def pick_random_status(*, excluding=None, seed=None):
    if len(RANDOM_STATUSES) <= 1:
        return RANDOM_STATUSES[0]
    normalized_excluding = (excluding or '').strip()
    candidates = (
        tuple(status for status in RANDOM_STATUSES if status != normalized_excluding)
        if normalized_excluding else RANDOM_STATUSES
    )
    source = candidates or RANDOM_STATUSES
    generator = random.Random(seed)
    return source[generator.randrange(len(source))]
