"""empty message

Revision ID: 43dd59c9654e
Revises: d4720d269098
Create Date: 2022-01-15 12:08:08.921473

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '43dd59c9654e'
down_revision = 'd4720d269098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_room_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('participants_room_id_fkey', 'participants', type_='foreignkey')
    op.drop_constraint('participants_user_id_fkey', 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'participants', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key('participants_user_id_fkey', 'participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key('participants_room_id_fkey', 'participants', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_room_id_fkey', 'messages', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###
