"""empty message

Revision ID: a7bfc14eac5f
Revises: c42f94e1433d
Create Date: 2022-05-12 13:19:43.667145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'a7bfc14eac5f'
down_revision = 'c42f94e1433d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_rooms_last_update', table_name='rooms')
    op.create_index(op.f('ix_rooms_updated_at'), 'rooms', ['updated_at'], unique=False)
    op.drop_column('rooms', 'last_update')
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.add_column('rooms', sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_rooms_updated_at'), table_name='rooms')
    op.create_index('ix_rooms_last_update', 'rooms', ['last_update'], unique=False)
    op.drop_column('rooms', 'updated_at')
    # ### end Alembic commands ###
