"""empty message

Revision ID: c42f94e1433d
Revises: 43dd59c9654e
Create Date: 2022-05-10 16:26:31.316286

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c42f94e1433d'
down_revision = '43dd59c9654e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('picture', sa.String(length=255), nullable=True))
    op.add_column('rooms', sa.Column('is_group', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_column('rooms', 'is_group')
    op.drop_column('rooms', 'picture')
    # ### end Alembic commands ###
