"""empty message

Revision ID: d4720d269098
Revises: 7a48a36c0313
Create Date: 2022-01-15 12:05:40.777294

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd4720d269098'
down_revision = '7a48a36c0313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participants_user_id_fkey', 'participants', type_='foreignkey')
    op.drop_constraint('participants_room_id_fkey', 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'participants', 'users', ['user_id'], ['id'])
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_index('idx_user_checkins_geog', table_name='user_checkins')
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_index('idx_users_last_geog', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_last_geog', 'users', ['last_geog'], unique=False)
    op.alter_column('users', 'last_geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.create_index('idx_user_checkins_geog', 'user_checkins', ['geog'], unique=False)
    op.alter_column('user_checkins', 'geog',
               existing_type=geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key('participants_room_id_fkey', 'participants', 'users', ['room_id'], ['id'])
    op.create_foreign_key('participants_user_id_fkey', 'participants', 'rooms', ['user_id'], ['id'])
    # ### end Alembic commands ###
